// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using api.Infrastructure.Data;

#nullable disable

namespace api.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260214172643_AddOutcomeWorkflowEnforcement")]
    partial class AddOutcomeWorkflowEnforcement
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("api.Domain.Entities.AuditEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Context")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("PerformedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("PerformedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RecruitmentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RecruitmentId", "PerformedAt")
                        .HasDatabaseName("IX_AuditEntries_RecruitmentId_PerformedAt");

                    b.ToTable("AuditEntries", (string)null);
                });

            modelBuilder.Entity("api.Domain.Entities.Candidate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("CurrentWorkflowStepId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("DateApplied")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Email")
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<string>("FullName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsCompleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<Guid>("RecruitmentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RecruitmentId")
                        .HasDatabaseName("IX_Candidates_RecruitmentId");

                    b.HasIndex("RecruitmentId", "Email")
                        .IsUnique()
                        .HasDatabaseName("UQ_Candidates_RecruitmentId_Email")
                        .HasFilter("[Email] IS NOT NULL");

                    b.ToTable("Candidates", (string)null);
                });

            modelBuilder.Entity("api.Domain.Entities.CandidateDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BlobStorageUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<Guid>("CandidateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DocumentSource")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("WorkdayCandidateId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CandidateId")
                        .HasDatabaseName("IX_CandidateDocuments_CandidateId");

                    b.ToTable("CandidateDocuments", (string)null);
                });

            modelBuilder.Entity("api.Domain.Entities.CandidateOutcome", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CandidateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("RecordedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("WorkflowStepId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CandidateId", "WorkflowStepId")
                        .HasDatabaseName("IX_CandidateOutcomes_CandidateId_WorkflowStepId");

                    b.ToTable("CandidateOutcomes", (string)null);
                });

            modelBuilder.Entity("api.Domain.Entities.ImportDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BlobStorageUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("CandidateName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("ImportSessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MatchStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<Guid?>("MatchedCandidateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("WorkdayCandidateId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ImportSessionId")
                        .HasDatabaseName("IX_ImportDocuments_ImportSessionId");

                    b.ToTable("ImportDocuments", (string)null);
                });

            modelBuilder.Entity("api.Domain.Entities.ImportSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CreatedCount")
                        .HasColumnType("int");

                    b.Property<int>("ErroredCount")
                        .HasColumnType("int");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("FlaggedCount")
                        .HasColumnType("int");

                    b.Property<string>("OriginalBundleBlobUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<int?>("PdfSplitCandidates")
                        .HasColumnType("int");

                    b.Property<int>("PdfSplitErrors")
                        .HasColumnType("int");

                    b.Property<int?>("PdfTotalCandidates")
                        .HasColumnType("int");

                    b.Property<Guid>("RecruitmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SourceFileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("TotalRows")
                        .HasColumnType("int");

                    b.Property<int>("UpdatedCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RecruitmentId")
                        .HasDatabaseName("IX_ImportSessions_RecruitmentId");

                    b.ToTable("ImportSessions", (string)null);
                });

            modelBuilder.Entity("api.Domain.Entities.Recruitment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("JobRequisitionId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Recruitments", (string)null);
                });

            modelBuilder.Entity("api.Domain.Entities.RecruitmentMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset>("InvitedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("RecruitmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_RecruitmentMembers_UserId");

                    b.HasIndex("RecruitmentId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("UQ_RecruitmentMembers_RecruitmentId_UserId");

                    b.ToTable("RecruitmentMembers", (string)null);
                });

            modelBuilder.Entity("api.Domain.Entities.WorkflowStep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<Guid>("RecruitmentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RecruitmentId")
                        .HasDatabaseName("IX_WorkflowSteps_RecruitmentId");

                    b.HasIndex("RecruitmentId", "Name")
                        .IsUnique()
                        .HasDatabaseName("UQ_WorkflowSteps_RecruitmentId_Name");

                    b.ToTable("WorkflowSteps", (string)null);
                });

            modelBuilder.Entity("api.Domain.Entities.Candidate", b =>
                {
                    b.HasOne("api.Domain.Entities.Recruitment", null)
                        .WithMany()
                        .HasForeignKey("RecruitmentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("api.Domain.Entities.CandidateDocument", b =>
                {
                    b.HasOne("api.Domain.Entities.Candidate", null)
                        .WithMany("Documents")
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("api.Domain.Entities.CandidateOutcome", b =>
                {
                    b.HasOne("api.Domain.Entities.Candidate", null)
                        .WithMany("Outcomes")
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("api.Domain.Entities.ImportDocument", b =>
                {
                    b.HasOne("api.Domain.Entities.ImportSession", null)
                        .WithMany("ImportDocuments")
                        .HasForeignKey("ImportSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("api.Domain.Entities.ImportSession", b =>
                {
                    b.OwnsMany("api.Domain.ValueObjects.ImportRowResult", "RowResults", b1 =>
                        {
                            b1.Property<Guid>("ImportSessionId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAddOrUpdate();

                            b1.Property<int>("Action");

                            b1.Property<string>("CandidateEmail");

                            b1.Property<DateTimeOffset?>("DateApplied");

                            b1.Property<string>("ErrorMessage");

                            b1.Property<string>("FullName");

                            b1.Property<string>("Location");

                            b1.Property<Guid?>("MatchedCandidateId");

                            b1.Property<string>("PhoneNumber");

                            b1.Property<string>("Resolution");

                            b1.Property<int>("RowNumber");

                            b1.HasKey("ImportSessionId", "__synthesizedOrdinal");

                            b1.ToTable("ImportSessions");

                            b1.ToJson("RowResults");

                            b1.WithOwner()
                                .HasForeignKey("ImportSessionId");
                        });

                    b.Navigation("RowResults");
                });

            modelBuilder.Entity("api.Domain.Entities.RecruitmentMember", b =>
                {
                    b.HasOne("api.Domain.Entities.Recruitment", null)
                        .WithMany("Members")
                        .HasForeignKey("RecruitmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("api.Domain.Entities.WorkflowStep", b =>
                {
                    b.HasOne("api.Domain.Entities.Recruitment", null)
                        .WithMany("Steps")
                        .HasForeignKey("RecruitmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("api.Domain.Entities.Candidate", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("Outcomes");
                });

            modelBuilder.Entity("api.Domain.Entities.ImportSession", b =>
                {
                    b.Navigation("ImportDocuments");
                });

            modelBuilder.Entity("api.Domain.Entities.Recruitment", b =>
                {
                    b.Navigation("Members");

                    b.Navigation("Steps");
                });
#pragma warning restore 612, 618
        }
    }
}
